projects:
  app:
    schemaPath: schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: generated/prisma.graphql
    extensions:
      prisma: server/prisma.yml